spring:
  datasource:
    driver: com.mysql.cj.jdbc.Drive
    url: jdbc:mysql://localhost:3306/blog_vue_springboot?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.beishan.blog.model

server:
  port: 9000